# Generated by Django 5.2.4 on 2025-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiharu_system', '0002_loginattempt_accountlock_securitynotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlock',
            name='last_attempt_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
