# Generated by Django 5.2.4 on 2025-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiharu_system', '0004_aianalysisreport_bulkcheque_bulkchequeallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
